---
name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.6,3.8'
    strategy:
      matrix:
        python-version: ["3.6", "3.8"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install requirements
        run: pip install --upgrade pip setuptools wheel
      - name: Run tests
        run: "./test.bash"
